# Generated by Django 4.0.5 on 2023-01-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0002_alter_district_district_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.CharField(max_length=255, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='district.district')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.SmallIntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='clinic.clinic')),
            ],
        ),
    ]
