# Generated by Django 4.0.5 on 2023-01-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('price', models.SmallIntegerField()),
                ('price_description', models.TextField()),
                ('exclu_price', models.SmallIntegerField()),
                ('availability', models.JSONField()),
                ('language', models.IntegerField(choices=[(1, 'Chinese'), (2, 'English')], default=1)),
                ('category', models.ManyToManyField(to='doctor.category')),
                ('clinic', models.ManyToManyField(to='clinic.clinic')),
            ],
        ),
    ]
